# Site settings
title: Coding Stuff
email: marcelo.jacobus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Like when you do stuff by coding
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mjacobus.github.com" # the base hostname & protocol for your site
twitter_username: marcelo_jacobus
github_username:  mjacobus

# Build settings
markdown: kramdown
