# Site settings
title: Coding Stuff
email: marcelo.jacobus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Like when you do stuff by coding. Marcelo Jacobus' thoughts and notes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mjacobus.github.com" # the base hostname & protocol for your site
twitter_username: marcelo_jacobus
github_username:  mjacobus

# Build settings
markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
# tag_permalink_style: pretty

author:
  name     : 'Marcelo Jacobus'
  email    : marcelo.jacobus@gmail.com
  url      : http://mjacobus.github.io
  # facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/marcelo_jacobus
  github  : https://github.com/mjacobus

github: https://github.com/mjacobus
disqus_shortname: "mjacobusgithubio"
google_analytics: UA-61332006-1

# paginate: 2
# comments: true
# paginate_path: "/page/:num"

# sass:
#   style: :compressed
#   sass_dir: _sass
